<?php

abstract class BaseDBPage extends BasePage
{
    protected PDO $pdo;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->pdo = DB::getConnection();
    }
}